# Generated by Django 3.2.9 on 2022-04-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='client',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='shop',
        ),
        migrations.DeleteModel(
            name='Production',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.DeleteModel(
            name='ShopItem',
        ),
    ]
